### ISSUE TITLE
Can't open packs

### ISSUE THREAD

**Issue by BartyBoyy09** [Powerthegreat/Mine-Trading-Cards-Source-1.12.2#21]
If i try to open card packs it says: ''Zero cards where registered, thus zero cards were generated''. i dont know what the issue is. Can you help me?

**Comment by Powerthegreat** [comment]
Have you got a content pack installed in the correct location?

**Comment by BartyBoyy09** [comment]
What do you mean with that? How does a content pack work?

**Comment by Powerthegreat** [comment]
The mod doesn't come with any cards built-in, they all have to be added by content packs
You can get content packs on the discord (https://discord.gg/TWDcAaX) or from this mega link https://mega.nz/folder/Ssdl2YqI#XPktl7Ioj7s3j512T6Q1_Q
As of MTC version 3.1, they must be placed within a resource pack, which only needs to be active if you want to see images on the cards
Please re-read the mod's page if you still don't understand
