### ISSUE TITLE
Crashes with a few different mods

### ISSUE THREAD

**Issue by ireece1** [Powerthegreat/Mine-Trading-Cards-Source-1.12.2#4]
I have a pack that im trying to add MTC to but a few different mods are clashing with it, preventing it from starting up.

https://paste.dimdev.org/uzotizudut.mccrash

https://paste.dimdev.org/gilageyodo.mccrash

**Comment by Powerthegreat** [comment]
This is an issue with hasCapability on my binder, fixing now
