### ISSUE TITLE
No Cards?

### ISSUE THREAD

**Issue by BigMinionD** [Powerthegreat/Mine-Trading-Cards-Source-1.12.2#6]
No cards show when I load up the game. What do I do?

**Comment by Powerthegreat** [comment]
Have you installed a content pack?

**Comment by BigMinionD** [comment]
I downloaded the mod package which should include the content but when I leave the mod in the package it doesn't register and if I take it out it wont register the cards. The content pack is called mtc, BTW

**Comment by Powerthegreat** [comment]
Is there a folder called "mtc" in your Minecraft folder, and is the mtc .jar file in your mods folder?
It's possible you downloaded the 1.7.10 branch and are trying to load it in 1.12.2, or vice versa.
The 1.7.10 branch has the mod in a "1.7.10" folder, which is only loaded by forge 1.7.10.
The 1.12.2 branch does the same with a folder called "1.12.2".

**Comment by BigMinionD** [comment]
Yes, I have the folder, but I don't know how to use it.

**Comment by Powerthegreat** [comment]
What version of minecraft are you running, and what version of MTC have you installed?

**Comment by BigMinionD** [comment]
The Minecraft version I'm using it on is 1.7.10 and the mod version is 2.0.1.

**Comment by Powerthegreat** [comment]
Is forge loading the mod - in Minecraft, in the "mods" menu, does Mine Trading Cards show up?
Does your mtc folder contain folders called assets, cards, and editions, with files inside those from a set?

**Comment by Powerthegreat** [comment]
If you're still having issues, contact me on discord (https://discord.gg/TWDcAaX)
